dist: bionic

language: node_js

node_js: 10

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

before_script:
  - npx sui-mono phoenix --ci --no-root
  - npm run install:demos -- --ci
  - npm run install:themes

script:
  - export NODE_OPTIONS=–-max_old_space_size=8192
  - npm run build
  - npm run test

after_success:
  - rm -rf ./node_modules
  - npm i vercel@latest
  - vercel --token $NOW_TOKEN --confirm
