sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '6'
before_install:
- npm i -g npm@^3.0.0
- npm i -g surge
- npm i -g @schibstedspain/sui-studio
- npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
after_success:
- suistudio run-all npm i
- npm run deploy
- suistudio release
branches:
  only:
  - master
