dist: bionic

language: node_js

node_js: 10

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

before_script:
  - npx sui-mono phoenix --ci --no-root
  - npm run install:demos -- --ci
  - npm run install:themes
  - export NODE_OPTIONS=--max_old_space_size=4096
  - echo fs.inotify.max_user_instances=524288 | tee -a /etc/sysctl.conf && sysctl -p
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sysctl -p
  - echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

script:
  - npm run build
  - npm run test -- --ci

after_success:
  - rm -rf ./node_modules
  - npm i vercel@latest
  - vercel --token $NOW_TOKEN --confirm
