dist: bionic

language: node_js

services:
  - xvfb

branches:
  only: master

node_js: 12

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

before_script:
  # install npm packages
  - export SUI_CI_TOPIC=install
  - npx @s-ui/ci update-commit-status --state RUN
  - npx sui-mono phoenix --ci --no-root
  - npm run install:demos -- --ci
  - npm run install:themes
  # some tweaks for tests to work
  - export NODE_OPTIONS=--max_old_space_size=4096
  - echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sysctl -p
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sysctl -p
  - echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  - npx @s-ui/ci update-commit-status --state OK

script:
  # create the bundle
  - export SUI_CI_TOPIC=bundle
  - npx @s-ui/ci update-commit-status --state RUN
  - npm run build
  - npx @s-ui/ci update-commit-status --state OK
  # execute tests
  - export SUI_CI_TOPIC=tests
  - npx @s-ui/ci update-commit-status --state RUN
  - npm run test -- --ci
  - npx @s-ui/ci update-commit-status --state OK
  # deploy
  - export VERCEL_PARAMS=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo --prod; else echo; fi)
  - export SUI_CI_TOPIC=deploy
  - npx @s-ui/ci update-commit-status --state RUN
  - rm -rf ./node_modules
  - npm i vercel@latest --no-save --no-fund --no-audit
  - DEPLOYMENT_URL=$(vercel --token $NOW_TOKEN --confirm $VERCEL_PARAMS)
  - npx @s-ui/ci update-commit-status --state OK --url $DEPLOYMENT_URL

after_failure:
  - npx @s-ui/ci update-commit-status --state
