name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-skip:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  assign_pr_owner:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to creator
        uses: thomaseizinger/assign-pr-creator-action@v1.0.0
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  log:
    runs-on: ubuntu-latest
    outputs:
      coverage_statements_master: ${{ steps.coverage.outputs.coverage_statements_master }}
      coverage_branches_master: ${{ steps.coverage.outputs.coverage_branches_master }}
      coverage_functions_master: ${{ steps.coverage.outputs.coverage_functions_master }}
      coverage_lines_master: ${{ steps.coverage.outputs.coverage_lines_master }}
    steps:
      - name: Chekout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
      - name: Configure node@16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Master Coverage
        run: |
          mkdir coverage
          node scripts/get-master-coverage.js > ./coverage/coverage-master.json
          cat coverage/coverage-master.json
      - name: Log context
        uses: actions/github-script@v5
        id: coverage
        with:
          script: |
            const script = require('./scripts/github/exportCoverageFromMarkdown')
            await script({github, context, core, exec}, './README.md')

  log-later:
    runs-on: ubuntu-latest
    needs: log
    steps:
      - run: |
          echo ${{needs.log.outputs.coverage_statements_master}}
          echo ${{needs.log.outputs.coverage_branches_master}}
          echo ${{needs.log.outputs.coverage_functions_master}}
          echo ${{needs.log.outputs.coverage_lines_master}}
