name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-skip:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Redundant Builds
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

  install:
    needs: check-skip
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '~/.npm'
        key: "ubuntu-latest-node-v14-${{ hashFiles('**/package-lock.json') }}"
        restore-keys: |
          ubuntu-latest-node-v14-
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: |
        npx -p @s-ui/mono sui-mono phoenix --ci
        npm run install:demos -- --ci
        npm run install:themes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Lint
      run: npx @s-ui/lint

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Build dependencies
      run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: public

  testing:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - name: Install xvfb for headless testing
      run: sudo apt-get install xvfb

    - name: Setup Max User Watches for Testing
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - name: Testing
      run: |
        xvfb-run --auto-servernum npm run test -- --ci

  release:
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Release components
      run: npx @s-ui/ci@beta release
      env:
        GITHUB_EMAIL: cloud-accounts@scmspain.com
        GITHUB_USER: sui-bot
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy:
    needs: [build, testing]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: |
        npm i vercel@latest --no-save --no-fund --no-audit --no-optional --no-scripts
        DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --confirm $VERCEL_PARAMS)
      env:
        VERCEL_PARAMS: ${{ github.event_name != 'pull_request' && '--prod' || ''}}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
