name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Redundant Builds
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: |
        npx @s-ui/ci update-commit-status --state RUN
        npx -p @s-ui/mono sui-mono phoenix --ci
        npm run install:demos -- --ci
        npm run install:themes
        npx @s-ui/ci update-commit-status --state OK
      env:
        SUI_CI_TOPIC: install

    - name: Lint
      run: |
        npx @s-ui/ci update-commit-status --state RUN
        npm run lint
        npx @s-ui/ci update-commit-status --state OK
      env:
        SUI_CI_TOPIC: lint

    - name: Build dependencies
      run: |
        npx @s-ui/ci update-commit-status --state RUN
        npm run build
        npx @s-ui/ci update-commit-status --state OK
      env:
        SUI_CI_TOPIC=bundle
    
    - name: Testing
      run: |
        npx @s-ui/ci update-commit-status --state RUN
        npm run test -- --ci
        npx @s-ui/ci update-commit-status --state OK
      env:
        SUI_CI_TOPIC=tests

    - name: Release components
      run: |
        npx @s-ui/ci update-commit-status --state RUN
        npx @s-ui/ci release
        npx @s-ui/ci update-commit-status --state OK
      env:
        GITHUB_EMAIL: cloud-accounts@scmspain.com
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_USER: sui-bot
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        SUI_CI_TOPIC: release

    - name: Deploy
      run: |
        npx @s-ui/ci update-commit-status --state RUN
        rm -rf ./node_modules
        npm i vercel@latest --no-save --no-fund --no-audit --no-optional --no-scripts
        DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --confirm $VERCEL_PARAMS)
        npx @s-ui/ci update-commit-status --state OK --url $DEPLOYMENT_URL
      env:
        SUI_CI_TOPIC: deploy
        VERCEL_PARAMS: 
        VERCEL_TOKEN: {{secrets.VERCEL_TOKEN}}