name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-skip:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  assign_pr_owner:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to creator
        uses: thomaseizinger/assign-pr-creator-action@v1.0.0
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Build dependencies
        run: |
          npm run phoenix:ci
          npm run install:themes
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: public-folder
          path: public

  testing:
    runs-on: ubuntu-latest
    outputs:
      coverage_statements_pct_master: ${{ steps.coverage-master.outputs.coverage_statements_pct_master }}
      coverage_branches_pct_master: ${{ steps.coverage-master.outputs.coverage_branches_pct_master }}
      coverage_functions_pct_master: ${{ steps.coverage-master.outputs.coverage_functions_pct_master }}
      coverage_lines_pct_master: ${{ steps.coverage-master.outputs.coverage_lines_pct_master }}
      coverage_statements_pct_current: ${{ steps.coverage-current.outputs.coverage_statements_pct_current }}
      coverage_branches_pct_current: ${{ steps.coverage-current.outputs.coverage_branches_pct_current }}
      coverage_functions_pct_current: ${{ steps.coverage-current.outputs.coverage_functions_pct_current }}
      coverage_lines_pct_current: ${{ steps.coverage-current.outputs.coverage_lines_pct_current }}
      coverage_statements_total_current: ${{ steps.coverage-current.outputs.coverage_statements_total_current }}
      coverage_branches_total_current: ${{ steps.coverage-current.outputs.coverage_branches_total_current }}
      coverage_functions_total_current: ${{ steps.coverage-current.outputs.coverage_functions_total_current }}
      coverage_lines_total_current: ${{ steps.coverage-current.outputs.coverage_lines_total_current }}
      coverage_statements_covered_current: ${{ steps.coverage-current.outputs.coverage_statements_covered_current }}
      coverage_branches_covered_current: ${{ steps.coverage-current.outputs.coverage_branches_covered_current }}
      coverage_functions_covered_current: ${{ steps.coverage-current.outputs.coverage_functions_covered_current }}
      coverage_lines_covered_current: ${{ steps.coverage-current.outputs.coverage_lines_covered_current }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install xvfb for headless testing
        run: sudo apt-get install xvfb

      - name: Setup Max User Watches for Testing
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Testing
        run: |
          npm run phoenix:ci
          npm run lint
          xvfb-run --auto-servernum npm run test -- --ci --coverage
      - name: Log Master Coverage
        uses: actions/github-script@v5
        id: coverage-master
        with:
          script: |
            const script = require('./scripts/github/exportCoverageFromMarkdownShields')
            await script({github, context, core, exec}, './README.md')
      - name: Log Current Coverage
        uses: actions/github-script@v5
        id: coverage-current
        with:
          script: |
            const script = require('./scripts/github/exportCoverageFromMarkdownShields')
            await script({github, context, core, exec}, './coverage/coverage.json')
