# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: sudo apt-get install xvfb
      - run: npm run phoenix:ci
      - run: npm run install:themes
      - run: npm run lint
      - run: xvfb-run --auto-servernum npm run test -- --ci
